### ISSUE TITLE
supervised clustering of nodes

### ISSUE THREAD

**Issue by seekingdeep** [dsbrown1331/broil#1]
.

**Comment by dsbrown1331** [comment]
I'm very confused. Can you provide more details? Why would a customer be inconsistent and label the same item as belonging to two different clusters? This just seems like standard supervised learning, perhaps multi-class classification. Usually imitation learning is applied to sequential decision making tasks where multiple steps are taken to solve a problem.

**Comment by seekingdeep** [comment]
at different shops/grids the customers might prefer different items/nodes over the others, this is because when the customer enters a certain shop and starts evaluating an item/node, he is not only looking at this item, but he is looking at this item and it's context among the rest of the items in that shop. Which means that a change in a single item/node, is in-itself a change in the all-in-all context, which results in having different customer preferences and item clustering.

You don't need to over-think my example, because we as humans can easily see the pattern, which is all about the spatial position of a single item, but not as an individual, but as a member of the group.

You can consider this task as **"Context-Aware Classification"** or **"Accordant Clustering"** or **"Supervised Clustering"**

The question here is:
- can IL be trained to learn how to group/ cluster the items in each shop, will it understand the pattern.
- Do you require any resources, data, donations?

**Comment by dsbrown1331** [comment]
Yes you could probably use IL to train this, but it's not a good fit. You're just solving a clustering problem with known labels. This is not a problem setting where IL is typically used. I would look into clustering/supervised learning techniques. Especially multi-class problems.
